music_app/config/routes.rb
MusicApp::Application.routes.draw do
 
  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  root to: 'tracks#index'
  resources :users
  resources :sessions
  resources :tracks do
    resources :comments do
      post "flags", to: 'flags#create', as: 'flag'
    end
  
  end

end

   

music_app/app/models/ability.rb
  class Ability
    include CanCan::Ability
    
    def initialize(user)
      user ||= User.new

      case 
      when user.role?(:listener)
        can :read, Track
        can :create, Comment
        can :update, Comment, user_id: user.id
        can :create, Flag
        can :update, User, id: user.id
        can :read, User, id: user.id

      when user.role?(:artist)
        can :create, Track, user_id: user.id
        can :update, Track, user_id: user.id
        can :read, Track
        can :create, Comment
        can :update, Comment, user_id: user.id
        can :create, Flag
        can :update, User, id: user.id
        can :read, User, id: user.id

      when user.role?(:admin)
        can :manage, :all
        cannot :create, Flag
      
      else
        can :read, Track
        can :create, User

      end

      end
   end   

music_app/app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :commentable, :body, :user_id

  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  belongs_to :commentable, :polymorphic => true
  has_many :flags
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end

end

music_app/app/models/flag.rb
class Flag < ActiveRecord::Base

  attr_accessible :value, :comment_id, :user_id
  belongs_to :user
  belongs_to :comment

  validates :user_id, uniqueness: {scope: :comment_id}

end

music_app/app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :artwork_file, :description, :music_file, :name, :user_id

  mount_uploader :music_file, MusicFileUploader
  mount_uploader :artwork_file, ArtworkFileUploader
  belongs_to :user
  acts_as_commentable
  
  validates :name, presence: true
  validates :music_file, presence: true
  
end

music_app/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :email, :name, :profile, :password_confirmation, :password, :role, :background_image

  validates :password, presence: true, on: :create
  validates :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }

  def role?(role_to_compare)
      self.role.to_s == role_to_compare.to_s
  end

  has_many :tracks
  has_many :comments, dependent: :destroy
  
  ROLES = %w[artist listener]
  IMAGES = Dir.entries("#{Rails.root}/app/assets/images/background_images/").map { |f| f if !File.directory?(f) }.compact!

  def role_symbols
     [role.to_sym]
  end


end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user
  
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "You don't have permission to access that, I'm afraid - sorry."
    redirect_to root_url
  end

  private
    def current_user
      begin
          @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue ActiveRecord::RecordNotFound
        session[:user_id] = nil
      end
    end
  end

music_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  
  def edit
    @track = Track.find(params[:track_id])
    @comment = Comment.find(params[:id])
  end

  def create
    @track = Track.find(params[:track_id])
    @comment = Comment.build_from(@track, current_user.id, params[:comment][:body] )
    flash[:notice] = "You need to be logged in to comment" if !@comment.save
    redirect_to @track
  end

  def update
    @track = Track.find(params[:track_id])

    if @comment.update_attributes(params[:comment])
    redirect_to @track, notice: 'Track successfully updated.'
    else
      render action: "edit" 
    end   
  end

  def destroy
    @track = Track.find(params[:track_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @track
  end
  
end

music_app/app/controllers/flags_controller.rb
class FlagsController < ApplicationController

  def create
    @comment = Comment.find(params[:comment_id])
    flag = @comment.flags.new user_id: current_user.id 

    flag.save
    redirect_to @comment.commentable

    flash[:notice] = "That flag did not save - perhaps you already flagged this comment for review" if !flag.save
  end
  
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

 def create
   user = User.find_by_email(params[:email])
   if user && user.authenticate(params[:password])
     session[:user_id] = user.id
     redirect_to root_url, notice: "Logged in!"
   else
     flash.now.alert = "Invalid email or password"
     render "new"
   end
 end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  load_and_authorize_resource
  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find(params[:id])
    @comment = Comment.new
    @comments = @track.comment_threads
  end

  def new
    @track = Track.new
  end

  def edit
    @track = Track.find(params[:id])
  end

  def create
    current_user.tracks.create(params[:track])
    
    redirect_to tracks_path
  end

  def update
    @track = Track.find(params[:id])

      if @track.update_attributes(params[:track])
      redirect_to @track, notice: 'Track successfully updated.'
      else
        render action: "edit" 
      end    
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy

    redirect_to tracks_url 

  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tracks = @user.tracks
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

      if @user.save
         redirect_to "/sessions/new", notice: 'User was successfully created.'
      else
        render action: "new" 
      end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: "edit" 
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url 
   
  end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper

  def image_header(user)
    if user.background_image.present?
      user.background_image.to_s
    else
       User::IMAGES.sample
    end 

  end

end

music_app/app/views/comments/_comment.erb
<br><br><br><em><%= comment.body %></em><br>
- <i><%= comment.user.name %> &nbsp;&middot;&nbsp; <%= time_ago_in_words(comment.created_at) %> ago</i><br><br>

<% if can? :update, comment %>
  <%= link_to "Edit", edit_track_comment_path(@track, comment) %>
<% end %>
<% if can? :destroy, comment %>
  |<%= link_to 'Delete this comment', [@track, comment], method: :delete %> 
<% end %>

| <%= pluralize comment.flags.count, "Flag" %>
<% if current_user && can?(:create, Flag) %>
  | <%= link_to "Flag", track_comment_flag_path(@track, comment), method: "post" %> <br><br><br><br>

<% end %>

music_app/app/views/comments/_form.html.erb
<br>
<%= form_for([@track, @comment]) do |f| %>
  <div class="form-group">
    <%= f.text_field :body, class: "form-control", placeholder: "Comment" %>
  </div><br>
  <div class="actions">
    <%= submit_tag "Edit comment", class: "btn btn-primary" %>
  </div>
<% end %>

music_app/app/views/comments/edit.html.erb
<h2>Edit comment</h2>
<%= render 'form' %>

music_app/app/views/comments/new.html.erb
<h3>Add a comment</h3>
<%= render 'form' %>

music_app/app/views/comments/show.html.erb
<h3>Comments: <%= @comments %></h3>


<%= link_to 'Back', tracks_path %>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
          <ul class="nav navbar-nav">
            <% if params[:controller] != "tracks" && params[:action] != "index" %>
              <li><%= link_to "Cloudify", root_path %></li>
            <% end %>
            <li><%= link_to "Tracks", tracks_path %></li>
            <% if can? :create, Track %>
            <li><%= link_to "Add New Track", new_track_path %></li>
            <% end %> 
            <% if can? :manage, User %>
            <li><%= link_to "View All Users", users_path %></li>
            <% end %> 
          </ul>
             
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
            <li><%= link_to current_user.name, user_path(current_user.id) %></li>
            <li><%= link_to 'I\'m outta here!', '/logout' %></li>
            <% else %>
            <li><%= link_to 'Log in', new_session_path %></li>
            <li><%= link_to "I'm a new user", new_user_path %></li>
            <% end %>
          </ul>
     </div>
    </nav>
  </header>

  <main>
    <div class="container">
      <% if params[:controller] == "tracks" && params[:action] == "index" %>
        <div class="jumbotron">
        <h1>This is Cloudify</h1>
        <p>Seamless music sharing</p>
        </div>
        <% flash.each do |name, msg| %>
        <div class="flash-message flash-message-<%= name %>">
        <%= msg %>
        </div>
        <% end %>
      <% end %>


      <%= yield %>
    </div>
  </main>

  <footer>
    <div class="container">
      &copy; Kate Montgomery 2014
    </div>
  </footer>  


</body>
</html>

music_app/app/views/tracks/_form.html.erb
<div class="container">
      <%= form_for(@track) do |f| %>
      <% if @track.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>
        <ul>
        <% @track.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name,  class: "form-control", placeholder: "Track name" %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br />
      <%= f.text_field :description, class: "form-control", placeholder: "Description" %>
    </div>
    <div class="form-group">
      <%= f.label :music_file %><br />
      <%= f.file_field :music_file %>
    </div>
      <div class="form-group">
      <%= f.label :artwork_file %><br />
      <%= f.file_field :artwork_file  %>
      </div><br>
    <div class="actions">
      <%= submit_tag "Submit", class: "btn btn-primary" %>
    </div><br>
  <% end %>
</div>

music_app/app/views/tracks/_track.erb
<tr>
  <td><%= track.name %></td>
  <td><%= track.description %></td>
  <td><%= track.user.try :name %></td>
  <td><%= link_to 'Show', track %></td>

  <% if can? :update, @track %>
   <td> <%= link_to 'Edit', edit_track_path(track) %> </td>
  <% end %>

  <% if can? :destroy, @track %>
      <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure you want to delete this track?' } %> </td>
  <% end %>
</tr>

music_app/app/views/tracks/edit.html.erb
<h1>Edit track</h1>

<%= render 'form' %>

<br><%= link_to 'Show', @track %> | 
<%= link_to 'Back', tracks_path %>

music_app/app/views/tracks/index.html.erb
<div class="container">
  <h1>All tracks</h1>

  <table class="table">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="4">Owner</th>
    
    </tr>

  <%= render @tracks %>

  </table>
</div>

music_app/app/views/tracks/new.html.erb
<h1>Add new track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

music_app/app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="container">
    <h3><%= @track.user.name %>'s tracks</h3><br>
   <ul class="list-inline">
      <li><%= link_to image_tag(@track.artwork_file.thumb.url), @track.artwork_file.detail.url %></li>
      <br>
      <h4><li><b>Track name: </b><%= @track.name %></li> 
       <li><b>Description: </b><%= @track.description %></li></h4><br>
    <div class = "media">
      <%= audio_tag @track.music_file.url, controls: true %>
    </div>
  <% if can? :update, Track %>
  <li><%= link_to "Edit", edit_track_path %></li>
  <% end %> </ul> 
    <b>Last updated: </b><%= time_ago_in_words(@track.updated_at) %> ago<br><br>

    <h3>Add a comment:</h3>
    <%= form_for [@track, @comment], html: {role: "form"} do |f| %>
      <div class="form-group">
        <!-- <label for="body">Body</label> -->
        <%= f.text_area :body, rows: "5",  class: "form-control", placeholder: "Enter comment" %>
      </div>
      <div class="actions">
        <%= f.submit class: "btn btn-primary pull-right" %>
      </div><br>
    <% end %>

    <%= render @comments %>
  
   

<%= link_to 'Back', tracks_path %>

</div>

music_app/app/views/users/_form.html.erb
<div class="container">
    <div class="alert alert-error">
      <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control", placeholder: "Email address" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation,  class: "form-control", placeholder: "Password confirmation" %>
    </div>
    <div class="form-group">
      <%= f.label :profile %>
      <%= f.text_field :profile, class: "form-control", placeholder: "Tell us a bit about yourself" %>
    </div>
    <div>
    <div class="form-group">
      <%= f.label :background_image %>
      <%= f.collection_select :background_image, User::IMAGES, :to_s, :humanize %>
    </div>
    <div class="form-group">
      <%= f.label :role %>
      <%= f.collection_select :role, User::ROLES, :to_s, :humanize %>
    </div>
    <div class="actions"><%= submit_tag "Cloudify me", class: "btn btn-primary" %></div><br>
  <% end %>
</div>

music_app/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

music_app/app/views/users/index.html.erb
<div class="container">
  <h1>All users</h1>

  <table class="table">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Profile</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.profile %></td>
      <td><%= user.role %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </table>
</div>

music_app/app/views/users/new.html.erb
<h1>Create an account</h1>

<%= render 'form' %>

music_app/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<section class="profile theme-two">
  <h1 style="background-image: url('/assets/background_images/<%= image_header(@user) %>');"><%= @user.name %></h1>

  <% if can? :update, Track, id: @user.id %>  
  <h3><%= @user.name %>'s tracks</h3>

  <table class="table">
    <tr>
      <th>Name</th>
      <th colspan="4">Description</th>
    
    </tr>

  <%= render @tracks %>
 <% end %> 
  </table>
  

  <br>
  <ul class="list-inline">
    <li><b>Role: </b><%= @user.role %></li>
    <li><b>Email: </b><%= @user.email %></li>
    <li><b>Last updated: </b><%= time_ago_in_words(@user.updated_at) %> ago</li>
  </ul>

  <%= link_to 'Tracks', tracks_path %> |
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</section> 